import { Link } from '@inertiajs/react';
import { Eye, Pencil } from 'lucide-react';
import AdminDataTable, { type Column } from '@/components/admin/inventory/admin-data-table';
import { Button } from '@/components/ui/button';
import TradeInShell from '@/components/admin/trade-ins/trade-in-shell';
import TradeInStatusBadge from '@/components/admin/trade-ins/trade-in-status-badge';
import { formatCurrency, formatDate, tradeInVehicleName } from '@/components/admin/trade-ins/helpers';
import type { OfferPagination, TradeInFilters, TradeInOffer } from '@/components/admin/trade-ins/types';
export default function Index({ offers, filters = {} }: { offers: OfferPagination; filters?: TradeInFilters }) { const columns: Column<TradeInOffer>[] = [{ key: 'amount', label: 'Offer amount', sortable: true, render: (offer) => formatCurrency(offer.amount ?? offer.offer_amount) }, { key: 'expires_at', label: 'Expiration date', sortable: true, render: (offer) => formatDate(offer.expires_at ?? offer.expiration_date) }, { key: 'accepted_at', label: 'Customer acceptance', sortable: true, render: (offer) => offer.accepted_at ? formatDate(offer.accepted_at) : 'Not accepted' }, { key: 'status', label: 'Offer status', sortable: true, render: (offer) => <TradeInStatusBadge status={offer.status} /> }, { key: 'approval_status', label: 'Approval workflow', render: (offer) => <TradeInStatusBadge status={offer.approval_status} /> }, { key: 'trade_in_request', label: 'Related request', render: (offer) => offer.trade_in_request ? <Link className="hover:underline" href={`/admin/trade-ins/${offer.trade_in_request.id}`}>{tradeInVehicleName(offer.trade_in_request)}</Link> : `#${offer.trade_in_request_id ?? '—'}` }]; return <TradeInShell title="Trade-In Offers" description="Create, review, approve, and track customer trade-in offers."><AdminDataTable rows={offers} filters={filters} columns={columns} baseUrl="/admin/trade-in-offers" createUrl="/admin/trade-in-offers/create" createLabel="Create Offer" rowActions={(offer) => <div className="flex justify-end gap-1"><Button variant="ghost" size="icon" asChild><Link href={`/admin/trade-ins/${offer.trade_in_request_id ?? offer.trade_in_request?.id}`}><Eye className="size-4" /></Link></Button><Button variant="ghost" size="icon" asChild><Link href={`/admin/trade-in-offers/${offer.id}/edit`}><Pencil className="size-4" /></Link></Button></div>} /></TradeInShell>; }
