import { Form } from '@inertiajs/react';
import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import type { TradeInRequest } from './types';
export default function TradeInForm({ tradeInRequest, action, method = 'post' }: { tradeInRequest?: TradeInRequest; action: string; method?: 'post' | 'put' }) {
  return <Form action={action} method="post" className="grid max-w-4xl gap-4 rounded-xl border bg-card p-4">{({ errors, processing }) => <>{method === 'put' && <input type="hidden" name="_method" value="put" />}<div className="grid gap-4 md:grid-cols-3"><div className="space-y-2"><Label>Year</Label><Input name="year" type="number" defaultValue={tradeInRequest?.year ?? ''} /><InputError message={errors.year} /></div><div className="space-y-2"><Label>Make</Label><Input name="make" defaultValue={tradeInRequest?.make ?? ''} /><InputError message={errors.make} /></div><div className="space-y-2"><Label>Model</Label><Input name="model" defaultValue={tradeInRequest?.model ?? ''} /><InputError message={errors.model} /></div><div className="space-y-2"><Label>VIN</Label><Input name="vin" defaultValue={tradeInRequest?.vin ?? ''} /><InputError message={errors.vin} /></div><div className="space-y-2"><Label>Mileage</Label><Input name="mileage" type="number" defaultValue={tradeInRequest?.mileage ?? ''} /><InputError message={errors.mileage} /></div><div className="space-y-2"><Label>Status</Label><Input name="status" defaultValue={tradeInRequest?.status ?? 'pending'} /><InputError message={errors.status} /></div><div className="space-y-2"><Label>Estimated value</Label><Input name="estimated_value" type="number" defaultValue={tradeInRequest?.estimated_value ?? ''} /></div><div className="space-y-2"><Label>Offered value</Label><Input name="offered_value" type="number" defaultValue={tradeInRequest?.offered_value ?? ''} /></div></div><div className="space-y-2"><Label>Condition report</Label><Textarea name="condition_report" rows={6} defaultValue={JSON.stringify(tradeInRequest?.condition_report ?? {}, null, 2)} /></div><Button className="w-fit" disabled={processing}>{processing ? 'Saving…' : 'Save trade-in request'}</Button></>}</Form>;
}
