import type { LeadRecord } from '@/components/admin/crm/types';
import type { CustomerRecord, TimelineEvent } from '@/components/admin/customers/types';
import type { Paginated } from '@/components/admin/inventory/types';

export interface TradeInVehicle { id?: number; title?: string; stock_number?: string; vin?: string; year?: number; make?: string | { name?: string }; model?: string | { name?: string }; mileage?: number; sale_price?: string | number; image_url?: string; [key: string]: unknown }
export interface TradeInUser { id?: number; name?: string; email?: string; phone?: string; first_name?: string; last_name?: string; avatar_url?: string }
export interface TradeInPhoto { id: number; url?: string; path?: string; alt_text?: string; caption?: string }
export interface TradeInOffer { id: number; trade_in_request_id?: number; valuation_id?: number; created_by?: number; offer_amount?: string | number; valid_until?: string; status?: string; notes?: string; terms?: Record<string, unknown>; accepted_at?: string; rejected_at?: string; created_at?: string; updated_at?: string; tradeInRequest?: TradeInRequest; valuation?: TradeInValuation; createdBy?: TradeInUser }
export interface TradeInInspection { id?: number; trade_in_request_id?: number; inspector_id?: number; inspection_date?: string; status?: string; condition_details?: Record<string, unknown>; notes?: string; estimated_repair_cost?: string | number; repair_recommendations?: string; photos?: TradeInPhoto[]; created_at?: string; updated_at?: string; tradeInRequest?: TradeInRequest; inspector?: TradeInUser }
export interface TradeInValuation { id?: number; trade_in_request_id?: number; trade_in_value?: string | number; wholesale_value?: string | number; retail_value?: string | number; valuation_method?: string; market_comparables?: Array<{ make?: string; model?: string; year?: number; mileage?: number; price?: string | number }>; adjustments?: string; notes?: string; created_at?: string; updated_at?: string; tradeInRequest?: TradeInRequest; valuationSource?: TradeInUser }
export interface TradeInRequest { id: number; user_id?: number; vehicle_id?: number; make?: string; model?: string; year?: number; vin?: string; mileage?: number; estimated_value?: string | number; offered_value?: string | number; status?: string; condition_report?: Record<string, unknown>; customer?: CustomerRecord; user?: TradeInUser; vehicle?: TradeInVehicle; desired_vehicle?: TradeInVehicle; desiredVehicle?: TradeInVehicle; assigned_user?: TradeInUser; assignedUser?: TradeInUser; photos?: TradeInPhoto[]; images?: TradeInPhoto[]; inspection?: TradeInInspection; valuation?: TradeInValuation; offers?: TradeInOffer[]; timeline?: TimelineEvent[]; notes?: Array<{ id: number; title?: string; body?: string; note?: string }>; documents?: Array<{ id: number; title?: string; name?: string; file_name?: string; url?: string }>; lead?: LeadRecord; finance_application?: { id: number; status?: string; amount?: string | number }; reservations?: Array<{ id: number; status?: string; vehicle?: TradeInVehicle }>; created_at?: string; updated_at?: string; [key: string]: unknown }
export type TradeInPagination = Paginated<TradeInRequest>;
export type InspectionPagination = Paginated<TradeInInspection>;
export type ValuationPagination = Paginated<TradeInValuation>;
export type TradeInFilters = Record<string, string | number | boolean | undefined>;
export type OfferPagination = Paginated<TradeInOffer>;
