import type { Paginated } from '@/components/admin/inventory/types';
import type { CustomerRecord, TimelineEvent } from '@/components/admin/customers/types';
import type { LeadRecord } from '@/components/admin/crm/types';

export interface TradeInVehicle { id?: number; title?: string; stock_number?: string; vin?: string; year?: number; make?: string | { name?: string }; model?: string | { name?: string }; mileage?: number; sale_price?: string | number; image_url?: string; [key: string]: unknown }
export interface TradeInUser { id?: number; name?: string; email?: string; phone?: string; first_name?: string; last_name?: string; avatar_url?: string }
export interface TradeInPhoto { id: number; url?: string; path?: string; alt_text?: string; caption?: string }
export interface TradeInOffer { id: number; trade_in_request_id?: number; amount?: string | number; offer_amount?: string | number; expires_at?: string; expiration_date?: string; accepted_at?: string; status?: string; approval_status?: string; notes?: string; created_at?: string; updated_at?: string; trade_in_request?: TradeInRequest }
export interface TradeInInspection { id?: number; status?: string; exterior?: Record<string, boolean | string>; interior?: Record<string, boolean | string>; mechanical?: Record<string, boolean | string>; tire_condition?: string; engine_condition?: string; transmission_condition?: string; electrical_systems?: string; damage_notes?: string; inspector_notes?: string; photos?: TradeInPhoto[]; updated_at?: string; [key: string]: unknown }
export interface TradeInValuation { id?: number; market_value?: string | number; estimated_resale_value?: string | number; repair_estimate?: string | number; final_trade_in_value?: string | number; adjustments?: Array<{ label?: string; amount?: string | number; reason?: string }> | Record<string, string | number>; approval_status?: string; approval_history?: TimelineEvent[]; updated_at?: string; [key: string]: unknown }
export interface TradeInRequest { id: number; user_id?: number; vehicle_id?: number; make?: string; model?: string; year?: number; vin?: string; mileage?: number; estimated_value?: string | number; offered_value?: string | number; status?: string; condition_report?: Record<string, unknown>; customer?: CustomerRecord; user?: TradeInUser; vehicle?: TradeInVehicle; desired_vehicle?: TradeInVehicle; desiredVehicle?: TradeInVehicle; assigned_user?: TradeInUser; assignedUser?: TradeInUser; photos?: TradeInPhoto[]; images?: TradeInPhoto[]; inspection?: TradeInInspection; valuation?: TradeInValuation; offers?: TradeInOffer[]; timeline?: TimelineEvent[]; notes?: Array<{ id: number; title?: string; body?: string; note?: string }>; documents?: Array<{ id: number; title?: string; name?: string; file_name?: string; url?: string }>; lead?: LeadRecord; finance_application?: { id: number; status?: string; amount?: string | number }; reservations?: Array<{ id: number; status?: string; vehicle?: TradeInVehicle }>; created_at?: string; updated_at?: string; [key: string]: unknown }
export type TradeInPagination = Paginated<TradeInRequest>;
export type TradeInFilters = Record<string, string | number | boolean | undefined>;
export type OfferPagination = Paginated<TradeInOffer>;
