import type { LeadRecord } from '@/components/admin/crm/types';
import type { CustomerRecord, TimelineEvent } from '@/components/admin/customers/types';
import type { Paginated } from '@/components/admin/inventory/types';

export interface ImportVehicle { id?: number; title?: string; stock_number?: string; vin?: string; year?: number; make?: string | { name?: string }; model?: string | { name?: string }; mileage?: number; sale_price?: string | number; image_url?: string; [key: string]: unknown }
export interface ImportUser { id?: number; name?: string; email?: string; phone?: string; first_name?: string; last_name?: string; avatar_url?: string }
export interface ImportSupplier { id?: number; name?: string; company_name?: string; email?: string; phone?: string; country?: string; address?: string; [key: string]: unknown }
export interface ImportShipment { id?: number; shipment_reference?: string; container_number?: string; shipping_line?: string; vessel?: string; current_location?: string; status?: string; estimated_arrival?: string; port_of_loading?: string; destination_port?: string; tracking_events?: TimelineEvent[]; customs_status?: string; [key: string]: unknown }
export interface Shipment { id: number; vehicle_import_id?: number; tracking_number?: string; carrier?: string; origin?: string; destination?: string; status?: string; current_location?: string; estimated_arrival?: string; actual_arrival?: string; metadata?: Record<string, unknown>; vehicleImport?: ImportRequest; created_at?: string; updated_at?: string; [key: string]: unknown }
export interface ImportDocument { id: number; vehicle_import_id?: number; name?: string; type?: string; path?: string; verified_at?: string; created_at?: string; updated_at?: string; [key: string]: unknown }
export interface ImportPayment { id: number; vehicle_import_id?: number; payment_id?: number; payment_reference?: string; amount?: string | number; currency?: string; payment_type?: string; status?: string; due_date?: string; paid_at?: string; notes?: string; metadata?: Record<string, unknown>; vehicleImport?: ImportRequest; payment?: { id: number; amount?: string | number }; created_at?: string; updated_at?: string; [key: string]: unknown }
export interface ImportRequest { id: number; user_id?: number; supplier_id?: number; vehicle_id?: number; reference_number?: string; origin_country?: string; destination_port?: string; estimated_cost?: string | number; status?: string; request_data?: Record<string, unknown>; customer?: CustomerRecord; user?: ImportUser; supplier?: ImportSupplier; vehicle?: ImportVehicle; shipment?: ImportShipment; documents?: ImportDocument[]; payments?: ImportPayment[]; timeline?: TimelineEvent[]; notes?: Array<{ id: number; title?: string; body?: string; note?: string }>; lead?: LeadRecord; finance_application?: { id: number; status?: string; amount?: string | number }; trade_in?: { id: number; status?: string }; assigned_user?: ImportUser; assignedUser?: ImportUser; estimated_arrival?: string; payment_status?: string; current_stage?: string; shipping_method?: string; port_of_loading?: string; created_at?: string; updated_at?: string; [key: string]: unknown }
export type ImportPagination = Paginated<ImportRequest>;
export type ImportFilters = Record<string, string | number | boolean | undefined>;
export type ShipmentPagination = Paginated<Shipment>;
export type DocumentPagination = Paginated<ImportDocument>;
export type PaymentPagination = Paginated<ImportPayment>;
