import { Form } from '@inertiajs/react';
import InspectionChecklist from '@/components/admin/trade-ins/inspection-checklist';
import TradeInShell, { TradeInBackButton } from '@/components/admin/trade-ins/trade-in-shell';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { tradeInVehicleName } from '@/components/admin/trade-ins/helpers';
import type { TradeInRequest } from '@/components/admin/trade-ins/types';
export default function Edit({ tradeInRequest }: { tradeInRequest: TradeInRequest }) { const inspection = tradeInRequest.inspection; return <TradeInShell title="Edit Vehicle Inspection" description={tradeInVehicleName(tradeInRequest)} actions={<TradeInBackButton href={`/admin/trade-ins/${tradeInRequest.id}/inspection`} />}><Form action={`/admin/trade-ins/${tradeInRequest.id}/inspection`} method="post" className="space-y-4"><input type="hidden" name="_method" value="put" /><InspectionChecklist editable values={{ exterior: inspection?.exterior, interior: inspection?.interior, mechanical: inspection?.mechanical }} /><div className="grid gap-4 rounded-xl border bg-card p-4 md:grid-cols-2"><div className="space-y-2"><Label>Status</Label><Input name="status" defaultValue={inspection?.status ?? 'pending'} /></div><div className="space-y-2"><Label>Tire condition</Label><Input name="tire_condition" defaultValue={inspection?.tire_condition ?? ''} /></div><div className="space-y-2"><Label>Engine condition</Label><Input name="engine_condition" defaultValue={inspection?.engine_condition ?? ''} /></div><div className="space-y-2"><Label>Transmission condition</Label><Input name="transmission_condition" defaultValue={inspection?.transmission_condition ?? ''} /></div><div className="space-y-2 md:col-span-2"><Label>Electrical systems</Label><Input name="electrical_systems" defaultValue={inspection?.electrical_systems ?? ''} /></div><div className="space-y-2"><Label>Damage notes</Label><Textarea name="damage_notes" rows={5} defaultValue={inspection?.damage_notes ?? ''} /></div><div className="space-y-2"><Label>Inspector notes</Label><Textarea name="inspector_notes" rows={5} defaultValue={inspection?.inspector_notes ?? ''} /></div><Button className="w-fit">Save inspection</Button></div></Form></TradeInShell>; }
