import { Link } from '@inertiajs/react';
import { Pencil } from 'lucide-react';
import InspectionChecklist from '@/components/admin/trade-ins/inspection-checklist';
import TradeInShell, { TradeInBackButton } from '@/components/admin/trade-ins/trade-in-shell';
import TradeInStatusBadge from '@/components/admin/trade-ins/trade-in-status-badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { imageUrl, tradeInVehicleName } from '@/components/admin/trade-ins/helpers';
import type { TradeInRequest } from '@/components/admin/trade-ins/types';
export default function Show({ tradeInRequest }: { tradeInRequest: TradeInRequest }) { const inspection = tradeInRequest.inspection; return <TradeInShell title="Vehicle Inspection" description={tradeInVehicleName(tradeInRequest)} actions={<><TradeInBackButton href={`/admin/trade-ins/${tradeInRequest.id}`} /><Button asChild><Link href={`/admin/trade-ins/${tradeInRequest.id}/inspection/edit`}><Pencil className="mr-2 size-4" />Edit inspection</Link></Button></>}><div className="space-y-4"><Card><CardHeader><CardTitle>Inspection status</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-4"><TradeInStatusBadge status={inspection?.status} /><p>Tires: {inspection?.tire_condition ?? '—'}</p><p>Engine: {inspection?.engine_condition ?? '—'}</p><p>Electrical: {inspection?.electrical_systems ?? '—'}</p></CardContent></Card><InspectionChecklist values={{ exterior: inspection?.exterior, interior: inspection?.interior, mechanical: inspection?.mechanical }} /><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Damage notes</CardTitle></CardHeader><CardContent>{inspection?.damage_notes ?? 'No damage notes recorded.'}</CardContent></Card><Card><CardHeader><CardTitle>Inspector notes</CardTitle></CardHeader><CardContent>{inspection?.inspector_notes ?? 'No inspector notes recorded.'}</CardContent></Card></div><Card><CardHeader><CardTitle>Image gallery</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{inspection?.photos?.length ? inspection.photos.map((photo) => <img key={photo.id} src={imageUrl(photo.url ?? photo.path)} alt={photo.alt_text ?? 'Inspection'} className="aspect-video rounded-lg object-cover" />) : <p className="text-sm text-muted-foreground">No inspection photos uploaded.</p>}</CardContent></Card></div></TradeInShell>; }
