import * as React from 'react';
import { Link, router } from '@inertiajs/react';
import { Copy, Eye, MoreHorizontal, Pencil, Star, Trash2 } from 'lucide-react';
import ConfirmationDialog from '@/components/admin/confirmation-dialog';
import InventoryShell from '@/components/admin/inventory/inventory-shell';
import AdminDataTable, { type Column } from '@/components/admin/inventory/admin-data-table';
import { formatCurrency, formatNumber, vehicleName } from '@/components/admin/inventory/helpers';
import type { AdminVehicle, Filters, Paginated } from '@/components/admin/inventory/types';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { admin } from '@/routes/admin';

export default function Index({ vehicles, filters = {} }: { vehicles: Paginated<AdminVehicle>; filters?: Filters }) { const [deleteId, setDeleteId] = React.useState<number | null>(null); const columns: Column<AdminVehicle>[] = [{ key: 'title', label: 'Vehicle', sortable: true, render: (v) => <div><Link className="font-medium hover:underline" href={admin.vehicles.show(v.id).url}>{vehicleName(v)}</Link><p className="text-xs text-muted-foreground">#{v.stock_number} · {v.vin}</p></div> }, { key: 'year', label: 'Year', sortable: true, render: (v) => v.year }, { key: 'sale_price', label: 'Price', sortable: true, render: (v) => formatCurrency(v.sale_price) }, { key: 'mileage', label: 'Mileage', sortable: true, render: (v) => `${formatNumber(v.mileage)} mi` }, { key: 'status', label: 'Status', render: (v) => <div className="flex gap-1"><Badge variant={v.is_featured ? 'default' : 'secondary'}>{v.is_featured ? 'Featured' : 'Standard'}</Badge>{v.is_certified ? <Badge variant="outline">Certified</Badge> : null}</div> }]; return <InventoryShell title="Vehicles" description="Manage vehicle inventory, publication status, pricing, and merchandising." actions={<Button asChild><Link href={admin.vehicles.create().url}>Create Vehicle</Link></Button>}><AdminDataTable rows={vehicles} filters={filters} columns={columns} baseUrl={admin.vehicles.index().url} createUrl={admin.vehicles.create().url} createLabel="Create Vehicle" rowActions={(vehicle) => <><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon"><MoreHorizontal className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild><Link href={admin.vehicles.show(vehicle.id).url}><Eye className="mr-2 size-4" />View</Link></DropdownMenuItem><DropdownMenuItem asChild><Link href={admin.vehicles.edit(vehicle.id).url}><Pencil className="mr-2 size-4" />Edit</Link></DropdownMenuItem><DropdownMenuItem onClick={() => router.patch((vehicle.is_featured ? admin.vehicles.unfeature(vehicle.id) : admin.vehicles.feature(vehicle.id)).url)}><Star className="mr-2 size-4" />{vehicle.is_featured ? 'Unfeature' : 'Feature'}</DropdownMenuItem><DropdownMenuItem onClick={() => router.post(admin.vehicles.duplicate(vehicle.id).url)}><Copy className="mr-2 size-4" />Duplicate</DropdownMenuItem><DropdownMenuItem onClick={() => router.patch(admin.vehicles.markSold(vehicle.id).url)}>Archive / mark sold</DropdownMenuItem><DropdownMenuItem onClick={() => setDeleteId(vehicle.id)} className="text-destructive"><Trash2 className="mr-2 size-4" />Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu><ConfirmationDialog open={deleteId === vehicle.id} onOpenChange={(open) => !open && setDeleteId(null)} title="Delete vehicle?" description="This removes the vehicle from active inventory." confirmLabel="Delete" trigger={<span />} onConfirm={() => router.delete(admin.vehicles.destroy(vehicle.id).url, { onFinish: () => setDeleteId(null) })} /></>} /></InventoryShell>; }
